apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: mysql
    spec:
      containers:
      - image: nginx:1.15.0
        name: nginx
        volumeMounts:
          - name: mi-volumen
            mountPath: /etc/mi-volumen
      volumes:
      - name: mi-volumen
        persistentVolumeClaim:
          claimName: mysql-pv-claim
