apiVersion: v1
data:
  app_data: kubernetes-data
  nombre: example-custom-configmap
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"app_data":"kubernetes-data","nombre":"example-custom-configmap"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"my-custom-configmap","namespace":"default"}}
  creationTimestamp: "2026-07-03T15:31:05Z"
  name: my-custom-configmap
  namespace: default
  resourceVersion: "211891"
  uid: 2d87e1ae-2911-429c-bf0d-32733a3a7ff8
