apiVersion: v1
data:
  ca: LS0...
  cert: LS0...
  key: LS0...
kind: Secret
metadata:
  creationTimeStamp: "2026-07-16T02:29:31Z"
  name: ingress-nginx-example
  namespace: ingress-nginx
  resourceVersion: "21726"
  uid: 9e0f0e05-9afb-4e76-9eff-859e49ca303b
type: Opaque
